import 'package:ibex_app/core/models/class_model.dart';
import 'package:ibex_app/core/supabase/supabase_client.dart';

class ClassService {
  final _client = SupabaseClientHelper.client;

  static const _selectQuery =
      '*, sections(name, grades(name)), teacher:users!classes_teacher_id_fkey(name)';

  /// Fetches all classes visible to the current user (RLS enforced).
  Future<List<ClassModel>> getMyClasses() async {
    final response = await _client
        .from('classes')
        .select(_selectQuery)
        .order('created_at', ascending: false);
    return response.map((e) => ClassModel.fromJson(e)).toList();
  }

  /// Fetches classes taught by the current teacher.
  Future<List<ClassModel>> getTeacherClasses() async {
    final userId = _client.auth.currentUser?.id;
    if (userId == null) return [];
    final response = await _client
        .from('classes')
        .select(_selectQuery)
        .eq('teacher_id', userId)
        .order('created_at', ascending: false);
    return response.map((e) => ClassModel.fromJson(e)).toList();
  }

  /// Fetches classes in a specific section.
  Future<List<ClassModel>> getClassesBySection(String sectionId) async {
    final response = await _client
        .from('classes')
        .select(_selectQuery)
        .eq('section_id', sectionId)
        .order('subject_name');
    return response.map((e) => ClassModel.fromJson(e)).toList();
  }

  /// Fetches a class by its class code (for enrollment).
  Future<ClassModel?> getClassByCode(String code) async {
    final response = await _client
        .from('classes')
        .select(_selectQuery)
        .eq('class_code', code)
        .maybeSingle();
    if (response == null) return null;
    return ClassModel.fromJson(response);
  }

  /// Fetches a single class by ID.
  Future<ClassModel?> getClassById(String id) async {
    final response = await _client
        .from('classes')
        .select(_selectQuery)
        .eq('id', id)
        .maybeSingle();
    if (response == null) return null;
    return ClassModel.fromJson(response);
  }

  /// Creates a new class
  Future<ClassModel> createClass({
    required String sectionId,
    required String subjectName,
    required String teacherId,
  }) async {
    final response = await _client
        .from('classes')
        .insert({
          'section_id': sectionId,
          'subject_name': subjectName,
          'teacher_id': teacherId,
          // class_code is auto-generated by a database trigger
        })
        .select(_selectQuery)
        .single();
    return ClassModel.fromJson(response);
  }

  /// Deletes a class by ID
  Future<void> deleteClass(String id) async {
    await _client.from('classes').delete().eq('id', id);
  }

  /// Gets the count of all classes.
  Future<int> getClassCount() async {
    final response = await _client.from('classes').select('id');
    return response.length;
  }
}
